// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "FIREBASE_WEB_API_KEY",
    appId: '1:698077454704:web:66618883ade93cf57c6fb5',
    messagingSenderId: '698077454704',
    projectId: 'location-tracker-app-naresh',
    authDomain: 'location-tracker-app-naresh.firebaseapp.com',
    storageBucket: 'location-tracker-app-naresh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAAjeWxfWfSLIyJRTlymawOe19JC-txA8',
    appId: '1:698077454704:android:6c28c169e32f8f8b7c6fb5',
    messagingSenderId: '698077454704',
    projectId: 'location-tracker-app-naresh',
    storageBucket: 'location-tracker-app-naresh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyOiK9RpGNEV9b0ml5wP3Vdz90Eseemx4',
    appId: '1:698077454704:ios:8a6a571cb752f9317c6fb5',
    messagingSenderId: '698077454704',
    projectId: 'location-tracker-app-naresh',
    storageBucket: 'location-tracker-app-naresh.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyOiK9RpGNEV9b0ml5wP3Vdz90Eseemx4',
    appId: '1:698077454704:ios:8a6a571cb752f9317c6fb5',
    messagingSenderId: '698077454704',
    projectId: 'location-tracker-app-naresh',
    storageBucket: 'location-tracker-app-naresh.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfAFU1UHT6WX2F9kvoKXQAdg6gewlcT0Y',
    appId: '1:698077454704:web:b267514e0efda35d7c6fb5',
    messagingSenderId: '698077454704',
    projectId: 'location-tracker-app-naresh',
    authDomain: 'location-tracker-app-naresh.firebaseapp.com',
    storageBucket: 'location-tracker-app-naresh.firebasestorage.app',
  );
}
